services:
  postgres:
    container_name: postgres-db
    image: postgres:16-alpine3.22
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./dbvolume:/var/lib/postgresql/data

  pgadmin:
    container_name: pdadmin
    image: dpage/pgadmin4:9.11
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - ./pgvolume:/var/lib/pgadmin

